# coding: utf-8

"""
ETAPI

External Trilium API

The version of the OpenAPI document: 1.0.0
Contact: zadam.apps@gmail.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from trilium_client.models.branch import Branch


class TestBranch(unittest.TestCase):
    """Branch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Branch:
        """Test Branch
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Branch`
        """
        model = Branch()
        if include_optional:
            return Branch(
                branch_id = 'evnnmvHTCgIn',
                note_id = 'evnnmvHTCgIn',
                parent_note_id = 'evnnmvHTCgIn',
                prefix = '',
                note_position = 56,
                is_expanded = True,
                utc_date_modified = '2021-12-31 19:18:11.930Z'
            )
        else:
            return Branch(
        )
        """

    def testBranch(self):
        """Test Branch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
