# coding: utf-8

"""
    ETAPI

    External Trilium API

    The version of the OpenAPI document: 1.0.0
    Contact: zadam.apps@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trilium_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_create_backup(self) -> None:
        """Test case for create_backup

        """
        pass

    def test_create_note(self) -> None:
        """Test case for create_note

        """
        pass

    def test_create_revision(self) -> None:
        """Test case for create_revision

        """
        pass

    def test_delete_attachment_by_id(self) -> None:
        """Test case for delete_attachment_by_id

        """
        pass

    def test_delete_attribute_by_id(self) -> None:
        """Test case for delete_attribute_by_id

        """
        pass

    def test_delete_branch_by_id(self) -> None:
        """Test case for delete_branch_by_id

        """
        pass

    def test_delete_note_by_id(self) -> None:
        """Test case for delete_note_by_id

        """
        pass

    def test_export_note_subtree(self) -> None:
        """Test case for export_note_subtree

        """
        pass

    def test_get_app_info(self) -> None:
        """Test case for get_app_info

        """
        pass

    def test_get_attachment_by_id(self) -> None:
        """Test case for get_attachment_by_id

        """
        pass

    def test_get_attachment_content(self) -> None:
        """Test case for get_attachment_content

        """
        pass

    def test_get_attribute_by_id(self) -> None:
        """Test case for get_attribute_by_id

        """
        pass

    def test_get_branch_by_id(self) -> None:
        """Test case for get_branch_by_id

        """
        pass

    def test_get_day_note(self) -> None:
        """Test case for get_day_note

        """
        pass

    def test_get_inbox_note(self) -> None:
        """Test case for get_inbox_note

        """
        pass

    def test_get_month_note(self) -> None:
        """Test case for get_month_note

        """
        pass

    def test_get_note_by_id(self) -> None:
        """Test case for get_note_by_id

        """
        pass

    def test_get_note_content(self) -> None:
        """Test case for get_note_content

        """
        pass

    def test_get_week_note(self) -> None:
        """Test case for get_week_note

        """
        pass

    def test_get_year_note(self) -> None:
        """Test case for get_year_note

        """
        pass

    def test_import_zip(self) -> None:
        """Test case for import_zip

        """
        pass

    def test_login(self) -> None:
        """Test case for login

        """
        pass

    def test_logout(self) -> None:
        """Test case for logout

        """
        pass

    def test_patch_attachment_by_id(self) -> None:
        """Test case for patch_attachment_by_id

        """
        pass

    def test_patch_attribute_by_id(self) -> None:
        """Test case for patch_attribute_by_id

        """
        pass

    def test_patch_branch_by_id(self) -> None:
        """Test case for patch_branch_by_id

        """
        pass

    def test_patch_note_by_id(self) -> None:
        """Test case for patch_note_by_id

        """
        pass

    def test_post_attachment(self) -> None:
        """Test case for post_attachment

        """
        pass

    def test_post_attribute(self) -> None:
        """Test case for post_attribute

        """
        pass

    def test_post_branch(self) -> None:
        """Test case for post_branch

        """
        pass

    def test_post_refresh_note_ordering(self) -> None:
        """Test case for post_refresh_note_ordering

        """
        pass

    def test_put_attachment_content_by_id(self) -> None:
        """Test case for put_attachment_content_by_id

        """
        pass

    def test_put_note_content_by_id(self) -> None:
        """Test case for put_note_content_by_id

        """
        pass

    def test_search_notes(self) -> None:
        """Test case for search_notes

        """
        pass


if __name__ == '__main__':
    unittest.main()
