# coding: utf-8

"""
    ETAPI

    External Trilium API

    The version of the OpenAPI document: 1.0.0
    Contact: zadam.apps@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trilium_client.models.app_info import AppInfo

class TestAppInfo(unittest.TestCase):
    """AppInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppInfo:
        """Test AppInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppInfo`
        """
        model = AppInfo()
        if include_optional:
            return AppInfo(
                app_version = '0.50.2',
                db_version = 194,
                sync_version = 25,
                build_date = '2022-02-09T22:52:36+01:00',
                build_revision = '23daaa2387a0655685377f0a541d154aeec2aae8',
                data_directory = '/home/user/data',
                clipper_protocol_version = '1.0',
                utc_date_time = '2022-03-07T21:54:25.277Z'
            )
        else:
            return AppInfo(
        )
        """

    def testAppInfo(self):
        """Test AppInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
