# coding: utf-8

"""
ETAPI

External Trilium API

The version of the OpenAPI document: 1.0.0
Contact: zadam.apps@gmail.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from trilium_client.models.create_note_def import CreateNoteDef


class TestCreateNoteDef(unittest.TestCase):
    """CreateNoteDef unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateNoteDef:
        """Test CreateNoteDef
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CreateNoteDef`
        """
        model = CreateNoteDef()
        if include_optional:
            return CreateNoteDef(
                parent_note_id = 'evnnmvHTCgIn',
                title = '',
                type = 'text',
                mime = 'application/json',
                content = '',
                note_position = 56,
                prefix = '',
                is_expanded = True,
                note_id = 'evnnmvHTCgIn',
                branch_id = 'evnnmvHTCgIn',
                date_created = '2021-12-31 20:18:11.930+0100',
                utc_date_created = '2021-12-31 19:18:11.930Z'
            )
        else:
            return CreateNoteDef(
                parent_note_id = 'evnnmvHTCgIn',
                title = '',
                type = 'text',
                content = '',
        )
        """

    def testCreateNoteDef(self):
        """Test CreateNoteDef"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
